
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-19T10:48:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb3765a6d14ea34613559e1fd39ca6928017b957",
 "version": "3.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
